appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a64e246e0700cedd99
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: tOG5MCTnoEaSyokgHJEOaxOHQMsDEDOG+qmjADzN8f/sPMWvF7Gz9vwG2ld8jy2GALuUiwSumPVMWGxuK4IKemHGWwiHmBZA7iY7tBDPMHloNekcOe3DVQf64VFH2WMmLSwqQJMxqgxX8q5jNB1wFQzHmc9b9Y8leV8mL5a8NGZH1Gnr/o3dbhMqoG4/NvwmyRb5W9/qzzA9vXjxeWebSQyM9cni9+4113PWkRZ65VIJnAIRidATz38ZhIacOarL1i6GMR41xTkyGZ2dehR6fIS4zgTFtV4hcgCmp1MCZrDEgvyjh+8FI7FbIMSo0aYdfOlPAVNJZhhQeoh09OoMUDRtwM5/v6fh3qNnsGvqCL+96rmH+WEbad6LLKMigXvTelm2QEFjLxKFRS5ZKclvYf2dmlc6XjYSkpS09kUH/45Cti+LuBhoStkyy4BzbLsNTaZ+aotmVDKnjxJxjIkVx6ElOFv1gx1Yl+CjG0F85NoE1o1iDmFt16hV92S1vAr881u0p6ndnff7RRjwU8heirmy5SeCQLdFl6eP/VqXonPZbH7+K9RxAc6n88psB3zlOI3sjJenknN4U9Nw+KMdLGlbL8fyO0TVogsddjjKDFJpPiplp/m7ou6cjPq57zJE4+MnBiiVFj7hb0XwYRCkAOhBAuT+wXuI34SAuxgyM8I=}
